### ISSUE TITLE
How to annotate invisible keypoints

### ISSUE THREAD

**Issue by briansst** [chahuja/pats#5]
Hi, thanks for your great work!
I am now expanding datasets which support more ids. I have some question about human keypoints.
As i observed, OpenPose do not support invisible keypoints, however, in pats dataset, invisible keypoints are still labelled. 
I would like to know how you label the invisible points by OpenPose. 
Can you give me some advice？or open source data preprocessing scripts :)

**Comment by chahuja** [comment]
Hi, I am glad you found it useful.
By ids do you mean more speakers?
Yes, in some cases the hands are not well annotated by openpose, probably due to occlusion or ambiguity. In those cases I use slerp (Spherical Linear Interpolation) to find the missing keypoints. This method does not work all the time, especially when the start of the sequence is not confidently predicted. Hence, I have had to discard a lot of samples that are listed in the missing_intervals.h5. In the short term, you can use the `pose/confidence` key (confidence of prediction is estimated by openpose) in the h5 files to estimate which keypoints were predicted with lesser confidence and either interpolate or discard them based on your usecase.

We are in the process of automating the pipeline for data collection (with preprocessing and postprocessing scripts), but I don't expect it to be released before the end of summer.

**Comment by briansst** [comment]
Yes, I'm expanding speakers with other language. 
 I get it, looking forward to scripts release.
Thanks!
