### ISSUE TITLE
Location of first joint (Neck).

### ISSUE THREAD

**Issue by DeepestNet** [chahuja/pats#6]
Hi, thank you very much for the nice dataset.
When I plot 52 joint points after reading .h5 file the first joint (I think it's the 'Neck' joint) appears in an unusual location far from other joint points (see the fig). Would you please let me know the reason behind it? 
I also have a lack of understanding about ['parents'.](https://github.com/chahuja/pats/blob/0a25505a409c48e015ac0c6b26da17daa1de7f29/data/skeleton.py#L40)

![image](https://user-images.githubusercontent.com/16849132/155666425-64c823e8-4372-4f4f-a9c8-c3cabdf57909.png)

**Comment by chahuja** [comment]
> 1. When I plot 52 joint points why does the first joint (I guess it is the Neck joint) always appear in a far location from other joints? 

Yes, that is normal. The data has been shifted back by the value of the neck joint position at every time step. So, the neck is now actually (0,0) for all time steps. This was done to effectively make the consistent across all speakers. If you would like the original data extracted using openpose, the way to do so would be adding the neck position to every other joint 

> 2. I also have a lack of understanding about ['parents'.]

Parents effectively represent the parent joint of each joint.  The exception is -1 which is assigned to the root node (i.e. Neck). This information is useful to draw the skeleton between the joint positions.

**Comment by xxu511** [comment]
Hi :))))  Thank you so much for provide such good dataset and the answer of the question.@DeepestNet @chahuja  I know it's been a long time now, Can i ask how you plot the joints? Now, i plot the joints by assuming every two continue column is for one joint since there are total 104 column and the joint order follow the order shown in the Joint_name function. I also assume the XY coordinate I read from pose/data would not need to do any future calculate.
![image](https://github.com/chahuja/pats/assets/100254883/a95ee4e0-6920-4fba-973e-4a21915c6f89)
But things become strange when I plot the each joint obviously this is not look like a upper human body. It's really confusing me. Any help would be apreciate. Thank you so much. 
![image](https://github.com/chahuja/pats/assets/100254883/afc39cd2-33d7-4067-89d5-1357afdfa91c)

**Comment by chahuja** [comment]
My guess is that you may be reshaping the 104 `pose` vector incorrectly. If you are reshaping the `pose` vector as `pose.reshape(2, 52)`, could you try reshaping it as `pose.reshape(52, 2)`. As it has been a while, I don't remember which is the correct order.
